### ISSUE TITLE
[Question] How to ignore selective files?

### ISSUE THREAD

**Issue by Kikobeats** [zeke/standard-markdown#9]
```bash
❯ standard-markdown
v8-tips/freeing-memory.md:11:5: 'foo' is already defined
workflow/scope.md:18:1: 'objt' is constant.
workflow/scope.md:18:1: 'objt' is constant.
workflow/scope.md:27:7: 'objt' is already defined
```

I want to ignore this files, but I don't want to use inline comment for do that. Could be possible providing a globby CLI pattern?

**Comment by zeke** [comment]
@Kikobeats I was waiting for someone to open this issue. :)

Currently, just a directory is supported, but I would happily accept a PR adding blob support.

Standard itself uses [deglob](https://github.com/flet/deglob) which wraps [glob](https://github.com/isaacs/node-glob). Don't know much about it, but remember seeing it at one point and maybe it would be helpful for implementing this.

cc @flet
